"use client";

import { useMemo } from "react";
import { Copy, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { useState } from "react";
import type { BuildSpec, BaseImage } from "@/types/catalog";

interface BuildPreviewProps {
  spec: Omit<BuildSpec, "id" | "createdAt" | "updatedAt">;
  baseImage?: BaseImage | null;
}

export function BuildPreview({ spec, baseImage }: BuildPreviewProps) {
  const [copied, setCopied] = useState(false);

  const dockerfile = useMemo(() => {
    const lines: string[] = [];

    // Header
    lines.push("# Generated by Daax Image Catalog");
    lines.push(`# Build Spec: ${spec.name}`);
    lines.push(`# Generated: ${new Date().toISOString()}`);
    lines.push("");

    // Base image
    const registry = baseImage?.registry || "docker.io/hardened-images/dhi";
    const repository = baseImage?.repository || spec.base.imageId;
    lines.push(`# Base image from hardened registry`);
    lines.push(`FROM ${registry}/${repository}:${spec.base.version}`);
    lines.push("");

    // Labels
    lines.push("# Labels");
    lines.push(`LABEL org.opencontainers.image.title="${spec.name}"`);
    if (spec.description) {
      lines.push(
        `LABEL org.opencontainers.image.description="${spec.description}"`,
      );
    }
    lines.push(`LABEL com.daax.spec.name="${spec.name}"`);

    if (spec.customizations?.labels) {
      Object.entries(spec.customizations.labels).forEach(([key, value]) => {
        lines.push(`LABEL ${key}="${value}"`);
      });
    }
    lines.push("");

    // Environment variables
    if (
      spec.customizations?.env &&
      Object.keys(spec.customizations.env).length > 0
    ) {
      lines.push("# Environment");
      Object.entries(spec.customizations.env).forEach(([key, value]) => {
        lines.push(`ENV ${key}=${value}`);
      });
      lines.push("");
    }

    // Features
    if (spec.features.length > 0) {
      lines.push("# Install devcontainer features");
      spec.features.forEach((feature, idx) => {
        const featureName = feature.featureId.replace(/-/g, "_");
        lines.push(`# Feature: ${feature.featureId}`);
        lines.push(
          `COPY --from=ghcr.io/devcontainers/features/${feature.featureId}:${feature.version} / /tmp/features/${featureName}/`,
        );

        // Build options string
        const optionVars = Object.entries(feature.options)
          .map(([key, value]) => {
            if (typeof value === "boolean") {
              return `${key.toUpperCase()}=${value}`;
            }
            return `${key.toUpperCase()}="${value}"`;
          })
          .join(" ");

        lines.push(`RUN cd /tmp/features/${featureName} && \\`);
        if (optionVars) {
          lines.push(`    ${optionVars} ./install.sh && \\`);
        } else {
          lines.push(`    ./install.sh && \\`);
        }
        lines.push(`    rm -rf /tmp/features/${featureName}`);
        lines.push("");
      });
    }

    // Cleanup
    lines.push("# Cleanup");
    lines.push(
      "RUN apt-get clean 2>/dev/null || apk cache clean 2>/dev/null || true && \\",
    );
    lines.push("    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*");

    return lines.join("\n");
  }, [spec, baseImage]);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(dockerfile);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-4">
      {/* Summary */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
        <div className="p-3 bg-muted rounded-lg">
          <div className="text-muted-foreground">Base Image</div>
          <div className="font-medium">
            {spec.base.imageId}:{spec.base.version}
          </div>
        </div>
        <div className="p-3 bg-muted rounded-lg">
          <div className="text-muted-foreground">Features</div>
          <div className="font-medium">{spec.features.length} selected</div>
        </div>
        <div className="p-3 bg-muted rounded-lg">
          <div className="text-muted-foreground">Output</div>
          <div className="font-medium truncate">{spec.output.repository}</div>
        </div>
        <div className="p-3 bg-muted rounded-lg">
          <div className="text-muted-foreground">Tags</div>
          <div className="font-medium">{spec.output.tags.join(", ")}</div>
        </div>
      </div>

      {/* Dockerfile Preview */}
      <div className="relative">
        <div className="flex items-center justify-between mb-2">
          <span className="text-sm font-medium">Generated Dockerfile</span>
          <Button variant="ghost" size="sm" onClick={handleCopy}>
            {copied ? (
              <>
                <Check className="h-4 w-4 mr-1" />
                Copied
              </>
            ) : (
              <>
                <Copy className="h-4 w-4 mr-1" />
                Copy
              </>
            )}
          </Button>
        </div>
        <ScrollArea className="h-[400px] rounded-lg border bg-muted/30">
          <pre className="p-4 text-xs font-mono">
            {dockerfile.split("\n").map((line, i) => (
              <div key={i} className="flex">
                <span className="w-8 text-muted-foreground select-none">
                  {i + 1}
                </span>
                <span
                  className={
                    line.startsWith("#") ? "text-muted-foreground" : ""
                  }
                >
                  {line}
                </span>
              </div>
            ))}
          </pre>
        </ScrollArea>
      </div>

      {/* Selected Features List */}
      {spec.features.length > 0 && (
        <div>
          <span className="text-sm font-medium">Selected Features</span>
          <div className="mt-2 space-y-2">
            {spec.features.map((feature) => (
              <div
                key={feature.featureId}
                className="flex items-center justify-between p-2 bg-muted rounded text-sm"
              >
                <span className="font-medium">{feature.featureId}</span>
                <span className="text-muted-foreground">
                  {Object.keys(feature.options).length} options configured
                </span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
