"use client";

import { useMemo } from "react";
import { Copy, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useState } from "react";
import type { BuildSpec } from "@/types/catalog";

interface BuildPreviewProps {
  spec: BuildSpec;
}

export function BuildPreview({ spec }: BuildPreviewProps) {
  const [copied, setCopied] = useState(false);

  const dockerfile = useMemo(() => {
    const lines: string[] = [];

    lines.push(`# Generated by Daax Provenance`);
    lines.push(`# Build: ${spec.name}`);
    lines.push(``);
    lines.push(`FROM ${spec.base.imageId}:${spec.base.version}`);
    lines.push(``);

    if (spec.customizations?.labels) {
      Object.entries(spec.customizations.labels).forEach(([key, value]) => {
        lines.push(`LABEL ${key}="${value}"`);
      });
      lines.push(``);
    }

    if (spec.customizations?.env) {
      Object.entries(spec.customizations.env).forEach(([key, value]) => {
        lines.push(`ENV ${key}="${value}"`);
      });
      lines.push(``);
    }

    if (spec.features.length > 0) {
      lines.push(`# Features`);
      spec.features.forEach((feature) => {
        lines.push(`# - ${feature.featureId}:${feature.version}`);
      });
      lines.push(``);
    }

    if (spec.customizations?.additionalInstructions) {
      lines.push(`# Custom instructions`);
      lines.push(spec.customizations.additionalInstructions);
      lines.push(``);
    }

    return lines.join("\n");
  }, [spec]);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(dockerfile);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="relative">
      <Button
        variant="ghost"
        size="icon"
        className="absolute top-2 right-2"
        onClick={handleCopy}
      >
        {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
      </Button>
      <pre className="p-4 rounded-lg bg-muted/50 border text-sm overflow-auto max-h-96">
        <code>{dockerfile}</code>
      </pre>
    </div>
  );
}
