/**
 * Docker-style name generator for git worktree branches
 * Generates adjective-noun combinations that are git-branch-friendly
 */

const ADJECTIVES = [
  "agile",
  "bold",
  "brave",
  "bright",
  "calm",
  "clever",
  "cosmic",
  "daring",
  "eager",
  "elegant",
  "fierce",
  "fleet",
  "focused",
  "gentle",
  "golden",
  "graceful",
  "grand",
  "happy",
  "humble",
  "inspired",
  "jolly",
  "jovial",
  "keen",
  "kind",
  "lively",
  "lucid",
  "merry",
  "mindful",
  "nimble",
  "noble",
  "optimal",
  "peaceful",
  "proud",
  "quick",
  "quiet",
  "radiant",
  "rapid",
  "serene",
  "silent",
  "steady",
  "swift",
  "tender",
  "tranquil",
  "unique",
  "valiant",
  "vibrant",
  "vivid",
  "warm",
  "wise",
  "zealous",
];

const NOUNS = [
  "anchor",
  "aurora",
  "beacon",
  "breeze",
  "canyon",
  "comet",
  "dawn",
  "delta",
  "echo",
  "ember",
  "falcon",
  "fjord",
  "flame",
  "forest",
  "glacier",
  "grove",
  "harbor",
  "horizon",
  "iris",
  "island",
  "jade",
  "jungle",
  "kelp",
  "kite",
  "lagoon",
  "lotus",
  "maple",
  "marsh",
  "meadow",
  "mountain",
  "nebula",
  "oasis",
  "ocean",
  "orchid",
  "peak",
  "phoenix",
  "pine",
  "quartz",
  "quasar",
  "reef",
  "river",
  "stream",
  "summit",
  "tundra",
  "valley",
  "waterfall",
  "zenith",
];

export interface NameGeneratorOptions {
  existingNames?: string[];
  maxAttempts?: number;
}

/**
 * Generates a 4-character random suffix using cryptographically secure randomness.
 *
 * Uses crypto.getRandomValues for better randomness than Math.random(),
 * avoiding predictable suffixes when Math.random() returns edge-case values.
 *
 * @returns A 4-character lowercase alphanumeric string (e.g., "a3f9", "x7k2")
 *
 * @example
 * generateSuffix() // Returns "a3f9"
 * generateSuffix() // Returns "k7x2"
 */
function generateSuffix(): string {
  const chars = "0123456789abcdefghijklmnopqrstuvwxyz";
  const array = new Uint8Array(4);
  crypto.getRandomValues(array);
  return Array.from(array, (byte) => chars[byte % chars.length]).join("");
}

/**
 * Generate a cryptographically secure random index in the range [0, length).
 * Uses crypto.getRandomValues for consistent randomness quality throughout
 * the name generation process.
 */
function getSecureRandomIndex(length: number): number {
  const array = new Uint32Array(1);
  crypto.getRandomValues(array);
  return array[0] % length;
}

/**
 * Generate a random adjective-noun name with short hash suffix
 * Format: adjective-noun-xxxx (e.g., swift-falcon-a3f9)
 * Uses cryptographically secure randomness for all selections.
 */
export function generateName(): string {
  const adjective = ADJECTIVES[getSecureRandomIndex(ADJECTIVES.length)];
  const noun = NOUNS[getSecureRandomIndex(NOUNS.length)];
  const suffix = generateSuffix();
  return `${adjective}-${noun}-${suffix}`;
}

/**
 * Generate a unique name that doesn't collide with existing names
 * With the 4-char suffix, collisions are extremely rare (1 in 1.6M per base name)
 */
export function generateUniqueName(options: NameGeneratorOptions = {}): string {
  const { existingNames = [], maxAttempts = 10 } = options;
  const existingSet = new Set(existingNames.map((n) => n.toLowerCase()));

  for (let i = 0; i < maxAttempts; i++) {
    const name = generateName();
    if (!existingSet.has(name)) {
      return name;
    }
  }

  // Fallback: use timestamp if somehow still colliding
  return `${generateName()}-${Date.now().toString(36)}`;
}

// NOTE: For comprehensive branch name validation (including security checks),
// use isValidBranchName from '@/lib/worktree-manager' instead.
// This simplified function is kept for backward compatibility with name generation.
/**
 * Check if a generated name is valid for use as a git branch name.
 * This is a simplified check for names generated by this module.
 * For external input validation, use isValidBranchName from worktree-manager.
 */
export function isValidGeneratedName(name: string): boolean {
  // Git branch naming rules (simplified for generated names)
  // - Must start with a letter
  // - Can contain letters, numbers, and hyphens
  // - Cannot have consecutive hyphens
  // - Must end with a letter or number
  // This pattern also allows single-character names (e.g., "a") for consistency
  return /^[a-z](?:[a-z0-9-]*[a-z0-9])?$/.test(name) && !name.includes("--");
}

/**
 * Get the total number of possible unique combinations
 * Base combinations × suffix combinations (36^4)
 */
export function getTotalCombinations(): number {
  const baseCombinations = ADJECTIVES.length * NOUNS.length;
  const suffixCombinations = Math.pow(36, 4); // 4-char base36 = 1,679,616
  return baseCombinations * suffixCombinations; // ~4.1 billion
}
