"use client";

import { cn } from "@/lib/utils";

interface SLSALevel {
  level: string;
  description: string;
  requirements: string;
  benefits: string;
  color: string;
}

const slsaLevels: SLSALevel[] = [
  {
    level: "SLSA 0",
    description: "No SLSA compliance.",
    requirements:
      "No provenance, no build controls, no guarantees about the software supply chain.",
    benefits:
      "No protection against supply chain attacks. Builds may be tampered with at any stage.",
    color: "bg-zinc-500/20 border-zinc-500/40",
  },
  {
    level: "SLSA 1",
    description: "Basic provenance documentation.",
    requirements:
      "Provenance (metadata showing how the package was built) must exist and be verifiable.",
    benefits:
      "Documentation, preventing honest mistakes, and inventorying components.",
    color: "bg-yellow-500/20 border-yellow-500/40",
  },
  {
    level: "SLSA 2",
    description: "Tamper-resistance of the build service.",
    requirements:
      "Provenance must be signed and generated by a hosted, dedicated build platform.",
    benefits:
      "Reduced attack surface and weak tamper protection for artifacts after the build process.",
    color: "bg-orange-500/20 border-orange-500/40",
  },
  {
    level: "SLSA 3",
    description: "Extra resistance to specific threats.",
    requirements:
      "Requires a hardened build platform that meets specific security controls to prevent falsification of provenance data during the build.",
    benefits:
      "Stronger protection against tampering during the build process itself.",
    color: "bg-cyan-500/20 border-cyan-500/40",
  },
  {
    level: "SLSA 4",
    description: "Highest levels of confidence and trust.",
    requirements:
      "Requires all dependencies to be specified and reviewed (e.g., two-party review), and builds must be hermetic and reproducible.",
    benefits:
      "Maximum security with thorough auditing and the highest guarantee of build integrity.",
    color: "bg-green-500/20 border-green-500/40",
  },
];

export function SLSALevelsTable({ className }: { className?: string }) {
  return (
    <div className={cn("w-full overflow-x-auto", className)}>
      <table className="w-full text-sm">
        <thead>
          <tr className="border-b border-border/50">
            <th className="text-left p-3 font-semibold text-primary whitespace-nowrap">
              Level
            </th>
            <th className="text-left p-3 font-semibold text-foreground">
              Description
            </th>
            <th className="text-left p-3 font-semibold text-foreground">
              Key Requirements (Build Track)
            </th>
            <th className="text-left p-3 font-semibold text-foreground">
              Focus/Benefits
            </th>
          </tr>
        </thead>
        <tbody>
          {slsaLevels.map((level, index) => (
            <tr
              key={level.level}
              className={cn(
                "border-b border-border/30 transition-colors hover:bg-muted/30",
                index === 0 && "bg-zinc-900/30",
              )}
            >
              <td className="p-3">
                <span
                  className={cn(
                    "inline-flex items-center px-2.5 py-1 rounded-md text-xs font-bold border whitespace-nowrap",
                    level.color,
                  )}
                >
                  {level.level}
                </span>
              </td>
              <td className="p-3 text-muted-foreground">{level.description}</td>
              <td className="p-3 text-muted-foreground">
                {level.requirements}
              </td>
              <td className="p-3 text-muted-foreground">{level.benefits}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
